### ISSUE TITLE
Exiting GUI shows mouse cursor

### ISSUE THREAD

**Issue by rckymtnrfc** [jakimfett/Werkbench#1]
I noticed sometimes, when I exit the crafting GUI for the Werkbench, usually after clicking anywhere in the dark area around the GUI, my mouse cursor stays visible, while still affecting POV.  

This video might make more sense - https://youtu.be/N5Wb9TiPNzE

**Comment by jakimfett** [comment]
Yup, I just realized I left a Mouse.setGrabbed(false) debugging call in the container code. It'll be fixed in the next alpha, thanks for reporting this!

**Comment by jakimfett** [comment]
Fixed, closing.
