### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by rckymtnrfc** [jakimfett/Werkbench#2]
Crash on startup with Werkbench-1.7.10-0.1.21

http://pastebin.com/m9HJyY7K

**Comment by jakimfett** [comment]
Yeah, I derped when adding the network stuffs last night, I think it's this line here: https://github.com/jakimfett/Werkbench/blob/master/src/main/java/werkbench/network/MessageHandler.java#L18

**Comment by jakimfett** [comment]
Fixed, closing.
