### ISSUE TITLE
Output Duplication Bug

### ISSUE THREAD

**Issue by rckymtnrfc** [jakimfett/Werkbench#3]
Upon entering the crafting recipe, the output on the Werkbench is empty and no items are able to be pulled out until I leave the GUI and reenter.  Then the display shows correctly and the output can be pulled one time.  You can't pull out additional items.

Also, reentering the GUI and removing items from the crafting grid allows the output to still be pulled out without using any resources.

**Comment by jakimfett** [comment]
Yeah, I've been trying to smack this one down since January. The dupe glitch goes away once the output slot syncs correctly (it dupes because the client thinks the materials are still in the crafting grid).

**Comment by rckymtnrfc** [comment]
I thought you might know about it, but when I noticed the duplication bug, I thought I should let you know.

**Comment by jakimfett** [comment]
Fixed in the latest build, get it from the [Werkbench CurseForge page](http://minecraft.curseforge.com/mc-mods/228653-werkbench).
